name             'yum-qemu-ev'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'apachev2'
issues_url       'https://github.com/osuosl-cookbooks/yum-qemu-ev/issues'
source_url       'https://github.com/osuosl-cookbooks/yum-qemu-ev'
description      'Installs/Configures yum-qemu-ev'
long_description 'Installs/Configures yum-qemu-ev'
version          '1.1.5'

depends          'base'
depends          'yum'
depends          'yum-centos'

supports         'centos', '~> 7.0'
